--1:
CREATE VIEW open_items AS
SELECT VENDORS.VENDOR_NAME, INVOICES.INVOICE_NUMBER, INVOICES.INVOICE_TOTAL, (INVOICES.INVOICE_TOTAL - INVOICES.PAYMENT_TOTAL - INVOICES.CREDIT_TOTAL) AS "BALANCE_DUE"
FROM AP.INVOICES
INNER JOIN AP.VENDORS
ON INVOICES.VENDOR_ID = VENDORS.VENDOR_ID
WHERE (INVOICES.INVOICE_TOTAL - INVOICES.PAYMENT_TOTAL - INVOICES.CREDIT_TOTAL) > 0
ORDER BY VENDORS.VENDOR_NAME ASC;

--2:
SELECT *
FROM OPEN_ITEMS
WHERE "BALANCE_DUE" >= 1000;

--3:
CREATE VIEW OPEN_ITEMS_SUMMARY AS
SELECT VENDOR_NAME, COUNT(INVOICE_NUMBER) AS "OPEN_ITEM_COUNT" , SUM("BALANCE_DUE") AS "OPEN_ITEM_TOTAL"
FROM OPEN_ITEMS
GROUP BY VENDOR_NAME
ORDER BY "OPEN_ITEM_TOTAL" DESC;

--4:
SELECT *
FROM OPEN_ITEMS_SUMMARY
WHERE ROWNUM <=5;

--5:
CREATE OR REPLACE VIEW VENDOR_ADDRESS AS 
SELECT VENDOR_ID, VENDOR_ADDRESS1, VENDOR_ADDRESS2, VENDOR_CITY, VENDOR_STATE, VENDOR_ZIP_CODE
FROM AP.VENDORS;

--6:
UPDATE 
    AP.VENDORS
SET 
    VENDOR_ADDRESS1 = '1990 Westwoof Blvd',
    VENDOR_ADDRESS2 = 'Ste 260'
WHERE 
    VENDOR_ID = 4;