--1:
SELECT CUSTOMER_LAST_NAME, CUSTOMER_FIRST_NAME
FROM OM.CUSTOMERS
ORDER BY CUSTOMER_LAST_NAME;

--2:
SELECT CUSTOMER_LAST_NAME, CUSTOMER_FIRST_NAME
FROM OM.CUSTOMERS
ORDER BY CUSTOMER_LAST_NAME DESC;

--3:
SELECT CUSTOMER_LAST_NAME, CUSTOMER_FIRST_NAME
FROM OM.CUSTOMERS
ORDER BY CUSTOMER_LAST_NAME , CUSTOMER_FIRST_NAME DESC;

--4:
SELECT CUSTOMER_LAST_NAME, CUSTOMER_FIRST_NAME
FROM OM.CUSTOMERS
ORDER BY 1 DESC;

--5:
SELECT CUSTOMER_FIRST_NAME AS FIRSTNAME, CUSTOMER_LAST_NAME AS "Last Name", CUSTOMER_CITY AS "'City'", CUSTOMER_STATE AS "*Cust-State*"
FROM OM.CUSTOMERS;

--6:
SELECT DISTINCT CUSTOMER_STATE
FROM OM.CUSTOMERS
ORDER BY 1;

--7:
SELECT DISTINCT CUSTOMER_FAX
FROM OM.CUSTOMERS
ORDER BY 1 DESC;

--8:
SELECT *
FROM OM.CUSTOMERS
WHERE ROWNUM<=4;

--9:
SELECT TITLE
FROM OM.ITEMS
WHERE LOWER(TITLE) LIKE '%road%';

--10:
SELECT TITLE, UNIT_PRICE
FROM OM.ITEMS
WHERE UNIT_PRICE LIKE '%.%';

--11:
SELECT TITLE, UNIT_PRICE
FROM OM.ITEMS
WHERE UNIT_PRICE NOT LIKE '%.%';

--12:
SELECT ORDER_ID, ORDER_QTY
FROM OM.ORDER_DETAILS
WHERE ORDER_QTY >= 2;

--13:
SELECT ORDER_ID
FROM OM.ORDER_DETAILS
WHERE MOD(ORDER_ID,13) = 0;

--14:
SELECT ORDER_ID, SHIPPED_DATE
FROM OM.ORDERS
WHERE SHIPPED_DATE IS NULL;

--15:
SELECT ORDER_ID, SHIPPED_DATE - ORDER_DATE AS "Number of days to ship"
FROM OM.ORDERS
WHERE SHIPPED_DATE - ORDER_DATE >=25;
