--1:
SELECT TO_CHAR(INVOICE_TOTAL, '$999,999.99') AS "Formatted"
FROM AP.INVOICES;

--2:
SELECT TO_CHAR(ROUND(INVOICE_TOTAL), '9.99EEEE') AS "Scientific notation"
FROM AP.INVOICES
WHERE ROWNUM <= 10;

--3:
SELECT TO_CHAR(INVOICE_DATE, 'MM/DD/YYYY') AS "Formatted Invoice Date"
FROM AP.INVOICES
WHERE ROWNUM <= 10;

--4:
SELECT *
FROM AP.INVOICES
WHERE INVOICE_DATE = '07-MAY-14';

--5:
SELECT *
FROM STUDENT.ENROLLMENT
WHERE TO_DATE(ENROLL_DATE) = '30-JAN-07';

--6:
SELECT CONCAT(CONCAT(CONCAT(CONCAT(CITY, ', '),STATE),' ' ), ZIP)AS "All Together with Concat"
FROM STUDENT.ZIPCODE
WHERE ROWNUM <=10;

--7:
SELECT CITY || ', ' || STATE || ' ' || ZIP AS "All Together with ||"
FROM STUDENT.ZIPCODE
WHERE ROWNUM<=10;

--8:
SELECT CITY, UPPER(CITY) AS "UPPER", LOWER(CITY) AS "LOWER", INITCAP(CITY) AS "MIXED"
FROM STUDENT.ZIPCODE
WHERE ROWNUM <= 10;

--9:
SELECT CITY
FROM STUDENT.ZIPCODE
WHERE LENGTH(CITY) BETWEEN 5 AND 9 AND ROWNUM<=10;

--10:
SELECT CITY, SUBSTR(CITY, 2,4) AS "Two through Four"
FROM STUDENT.ZIPCODE
WHERE ROWNUM<=10;

--11:
SELECT CITY, SUBSTR(CITY, -3) AS "Last Three"
FROM STUDENT.ZIPCODE
WHERE ROWNUM<=10;

--12:
SELECT STUDENT_ID, NVL(MIDTERM_GRADE, 0) AS "No Grade Found", FINALEXAM_GRADE, QUIZ_GRADE
FROM STUDENT.GRADE_SUMMARY;

--13:
SELECT STUDENT_ID, SALUTATION, REGEXP_REPLACE(SALUTATION, 'Dr.','Doctor') AS "New Salutation"
FROM STUDENT.STUDENT
WHERE SALUTATION LIKE 'Dr.';

--14:
SELECT STREET_ADDRESS, RTRIM(STREET_ADDRESS) AS "Trimmed Address"
FROM STUDENT.STUDENT
WHERE ROWNUM <=10;

--15:
SELECT TO_NUMBER('123.45', '9999.99') AS "String to Number"
FROM DUAL;

--16:
SELECT SQRT(4) AS "SQRT of 4", SQRT(0) AS "SQRT of 0"
FROM DUAL;