--1:
SELECT COUNT(*) AS "Number of Invoices"
FROM AP.INVOICES;

--2:
SELECT COUNT(*) AS "Number of Valid Payment Dates"
FROM AP.INVOICES
WHERE PAYMENT_DATE IS NOT NULL;

--3:
SELECT COUNT(*) AS "Number of Null Payment Dates"
FROM AP.INVOICES
WHERE PAYMENT_DATE IS NULL;

--4:
SELECT DISTINCT PAYMENT_DATE
FROM AP.INVOICES
WHERE PAYMENT_DATE IS NOT NULL
ORDER BY PAYMENT_DATE ASC;

--5:
SELECT DISTINCT COUNT(DISTINCT PAYMENT_DATE) AS "Number of Diff. Payment Dates"
FROM AP.INVOICES;

--6:
SELECT TO_CHAR(SUM(INVOICE_TOTAL), '$999,999.99') AS "Total Invoice Amount"
FROM AP.INVOICES;

--7:
SELECT TO_CHAR(SUM(INVOICE_TOTAL) / COUNT(INVOICE_TOTAL), '9999.999') AS "Average Invoice Amount"
FROM AP.INVOICES;

--8:
SELECT TO_CHAR(FLOOR(SUM(INVOICE_TOTAL) / COUNT(INVOICE_TOTAL)), '9999') AS "Average Invoice Amount"
FROM AP.INVOICES;

--9:
SELECT MIN(INVOICE_TOTAL) AS "Lowest Invoice Total", MAX(INVOICE_TOTAL) AS "Highest Invoice Total"
FROM AP.INVOICES;

--10:
SELECT TO_CHAR(MIN(INVOICE_TOTAL), '$999,999.99') AS "Lowest Invoice Total", TO_CHAR(FLOOR(MAX(INVOICE_TOTAL)), '$999,999.99') AS "Highest Invoice Total"
FROM AP.INVOICES;

--11:
SELECT VENDOR_NAME AS "Last Vendor"
FROM AP.VENDORS
WHERE ROWNUM <=1
ORDER BY VENDOR_NAME DESC;

--12:
SELECT MIN(INVOICE_DATE)
FROM AP.INVOICES;

--13:
SELECT  INVOICE_DATE, COUNT(INVOICE_DATE) AS "Invoices per Date"
FROM AP.INVOICES
GROUP BY INVOICE_DATE
ORDER BY INVOICE_DATE ASC;

--14:
SELECT INVOICE_TOTAL, COUNT(INVOICE_TOTAL) AS "Invoices Less Than $10.00"
FROM AP.INVOICES
WHERE INVOICE_TOTAL<10
GROUP BY INVOICE_TOTAL;

--15:
SELECT VENDOR_STATE, COUNT(VENDOR_STATE) AS "Vendors per State"
FROM AP.VENDORS
GROUP BY VENDOR_STATE
ORDER BY VENDOR_STATE ASC;

--16:
SELECT VENDOR_STATE, COUNT(VENDOR_STATE) AS "Vendors per State"
FROM AP.VENDORS
HAVING COUNT(*) >= 3
GROUP BY VENDOR_STATE
ORDER BY COUNT(*) DESC;

--17:
SELECT TERMS_ID, COUNT(TERMS_ID) AS "Number in Terms Id Category"
FROM AP.INVOICES
GROUP BY TERMS_ID;

--18:
SELECT INVOICE_DATE, COUNT(INVOICE_DATE) AS "Invoices per Date"
FROM AP.INVOICES
WHERE INVOICE_DATE BETWEEN '01-JUN-14' AND '30-JUN-14'
GROUP BY INVOICE_DATE
ORDER BY INVOICE_DATE ASC;

--19:
SELECT INVOICE_DATE, COUNT(INVOICE_DATE) AS "Invoices per Date"
FROM AP.INVOICES
HAVING INVOICE_DATE BETWEEN '01-JUN-14' AND '30-JUN-14'
GROUP BY INVOICE_DATE
ORDER BY INVOICE_DATE ASC;

--20:
SELECT INVOICE_DUE_DATE - INVOICE_DATE AS "Difference in Days", COUNT(*) AS "How Many?"
FROM AP.INVOICES
GROUP BY INVOICE_DUE_DATE - INVOICE_DATE
ORDER BY INVOICE_DUE_DATE - INVOICE_DATE DESC;